---
- name: HMC create and Install VIOS then accept license
  hosts: hmcs
  connection: local
  vars:
      curr_hmc_auth:
          username: hscroot
          password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              34656335616165343966323739633761653065346138623233633764353636373063313736373563
              6130373162376464666634363734303164396364656535350a663661636663323434386466383634
              63323432303833643864396130393133346666336661346432356433353035663038643833373332
              3664333762656138640a306539363765343261383363346532643639383938656434333564323139
              6365

  tasks:
      - name: List all VIOS Images
        ibm.power_hmc.vios:
            hmc_host: '{{ inventory_hostname }}'
            hmc_auth: "{{ curr_hmc_auth }}"
            state: listimages
        register: images_info

      - name: Stdout the VIOS Images Info
        ansible.builtin.debug:
            msg: '{{ images_info }}'

      - name: Copy Vios Image via SFTP
        ibm.power_hmc.vios:
              hmc_host: '{{ inventory_hostname }}'
              hmc_auth: "{{ curr_hmc_auth }}"
              system_name: name
              image_name: img_name
              sftp_server: server_IP
              sftp_auth:
                username: username
                password: password
              action: copy
        register: testout

      - name: Stdout the Copy vios info
        ansible.builtin.debug:
            msg: '{{ testout }}'

      - name: Delete Vios Image
        ibm.power_hmc.vios:
              hmc_host: '{{ inventory_hostname }}'
              hmc_auth: "{{ curr_hmc_auth }}"
              image_name: img_name
              action: delete

      - name: Create VIOS with user defined profile_name and io_slots
        ibm.power_hmc.vios:
            hmc_host: '{{ inventory_hostname }}'
            hmc_auth: "{{ curr_hmc_auth }}"
            system_name: <System_Name>
            name: demo_vios
            settings:
                profile_name: default
                io_slots: 21010010/none/0,21010018/none/0
            state: present
        register: testout

      - name: Stdout the created VIOS
        ansible.builtin.debug:
            msg: '{{ testout }}'

      - name: Install VIOS through nim server
        ibm.power_hmc.vios:
            hmc_host: '{{ inventory_hostname }}'
            hmc_auth: "{{ curr_hmc_auth }}"
            system_name: <System_Name>
            name: demo_vios
            nim_IP: <NIM Server IP>
            nim_gateway: <NIM Server Gateway>
            vios_IP: <VIOS IP>
            nim_subnetmask: <NIM SUBNETMASK>
            timeout: 70
            action: install
        register: testout

      - name: Stdout the VIOS config after install
        ansible.builtin.debug:
            msg: '{{ testout }}'

      - name: Accept VIOS License
        ibm.power_hmc.vios:
            hmc_host: '{{ inventory_hostname }}'
            hmc_auth: "{{ curr_hmc_auth }}"
            system_name: <System_Name>
            name: demo_vios
            action: accept_license
        register: testout

      - name: Stdout accept license report
        ansible.builtin.debug:
            msg: '{{ testout }}'